window.MVP_DATA = Object.freeze({
  payloadScope: "admin",
  group: {
    name: "Grupo Horizonte",
    period: "Posição demonstrativa · agosto de 2026",
    updatedAt: "01/09/2026 às 09:30",
  },
  companies: [
    {
      id: "aurora",
      name: "Aurora Alimentos",
      code: "EMP-001",
      approved: 2480000,
      distributed: 1750000,
      shareholders: 3,
      status: "in_progress",
      allocations: [
        { shareholderId: "ana", entitlement: 900000, percentage: 36.29 },
        { shareholderId: "caio", entitlement: 850000, percentage: 34.27 },
        { shareholderId: "lia", entitlement: 730000, percentage: 29.44 },
      ],
    },
    {
      id: "iris",
      name: "Íris Varejo",
      code: "EMP-002",
      approved: 1620000,
      distributed: 1170000,
      shareholders: 4,
      status: "attention",
      allocations: [
        { shareholderId: "ana", entitlement: 600000, percentage: 37.04 },
        { shareholderId: "caio", entitlement: 450000, percentage: 27.78 },
        { shareholderId: "lia", entitlement: 320000, percentage: 19.75 },
        { shareholderId: "horizon", entitlement: 250000, percentage: 15.43 },
      ],
    },
    {
      id: "vale",
      name: "Vale Logística",
      code: "EMP-003",
      approved: 1430000,
      distributed: 520000,
      shareholders: 3,
      status: "in_progress",
      allocations: [
        { shareholderId: "ana", entitlement: 500000, percentage: 34.97 },
        { shareholderId: "caio", entitlement: 480000, percentage: 33.57 },
        { shareholderId: "lia", entitlement: 450000, percentage: 31.46 },
      ],
    },
    {
      id: "holding",
      name: "Horizonte Gestão Patrimonial",
      code: "EMP-004",
      approved: 950000,
      distributed: 455000,
      shareholders: 2,
      status: "regular",
      allocations: [
        { shareholderId: "ana", entitlement: 250000, percentage: 26.32 },
        { shareholderId: "horizon", entitlement: 700000, percentage: 73.68 },
      ],
    },
  ],
  shareholders: [
    { id: "ana", name: "Ana Vale", initials: "AV", type: "PF", entitlement: 2250000, received: 1170000, status: "in_progress" },
    { id: "caio", name: "Caio Serra", initials: "CS", type: "PF", entitlement: 1780000, received: 1190000, status: "attention" },
    { id: "lia", name: "Lia Prado", initials: "LP", type: "PF", entitlement: 1500000, received: 1120000, status: "attention" },
    { id: "horizon", name: "Horizonte Participações", initials: "HP", type: "PJ", entitlement: 950000, received: 415000, status: "regular" },
  ],
  months: [
    { label: "Jan", value: 250000 },
    { label: "Fev", value: 380000 },
    { label: "Mar", value: 420000 },
    { label: "Abr", value: 560000 },
    { label: "Mai", value: 495000 },
    { label: "Jun", value: 470000 },
    { label: "Jul", value: 420000 },
    { label: "Ago", value: 250000 },
    { label: "Set", value: 650000 },
  ],
  movements: [
    { id: "mov-01", companyId: "aurora", shareholderId: "ana", date: "2026-01-15", amount: 250000, eventType: "Pagamento", method: "PIX", legacy: true, status: "effective", revision: 1 },
    { id: "mov-02", companyId: "aurora", shareholderId: "ana", date: "2026-02-10", amount: 290000, eventType: "Pagamento", method: "TED", legacy: true, status: "effective", revision: 1 },
    { id: "mov-03", companyId: "aurora", shareholderId: "caio", date: "2026-02-18", amount: 90000, eventType: "Crédito", method: "Transferência interna", legacy: true, status: "effective", revision: 1 },
    { id: "mov-04", companyId: "aurora", shareholderId: "caio", date: "2026-03-12", amount: 370000, eventType: "Pagamento", method: "PIX", legacy: true, status: "effective", revision: 1 },
    { id: "mov-05", companyId: "aurora", shareholderId: "lia", date: "2026-03-22", amount: 50000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-06", companyId: "aurora", shareholderId: "lia", date: "2026-04-08", amount: 310000, eventType: "Pagamento", method: "TED", legacy: true, status: "effective", revision: 1 },
    { id: "mov-07", companyId: "iris", shareholderId: "ana", date: "2026-04-20", amount: 250000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-08", companyId: "iris", shareholderId: "ana", date: "2026-05-06", amount: 130000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-09", companyId: "iris", shareholderId: "caio", date: "2026-05-14", amount: 250000, eventType: "Crédito", method: "Compensação", legacy: false, status: "effective", revision: 1 },
    { id: "mov-10", companyId: "iris", shareholderId: "lia", date: "2026-05-27", amount: 115000, eventType: "Pagamento", method: "TED", legacy: true, status: "effective", revision: 1 },
    { id: "mov-11", companyId: "iris", shareholderId: "lia", date: "2026-06-05", amount: 135000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-12", companyId: "iris", shareholderId: "horizon", date: "2026-06-10", amount: 30000, eventType: "Crédito", method: "Transferência interna", legacy: false, status: "effective", revision: 1 },
    { id: "mov-13", companyId: "vale", shareholderId: "ana", date: "2026-06-12", amount: 180000, eventType: "Pagamento", method: "TED", legacy: false, status: "effective", revision: 1 },
    { id: "mov-14", companyId: "vale", shareholderId: "caio", date: "2026-06-18", amount: 50000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-15", companyId: "vale", shareholderId: "caio", date: "2026-06-25", amount: 75000, eventType: "Pagamento", method: "PIX", legacy: false, status: "effective", revision: 1 },
    { id: "mov-16", companyId: "vale", shareholderId: "caio", date: "2026-07-03", amount: 95000, eventType: "Pagamento", method: "PIX", legacy: true, status: "effective", revision: 1 },
    { id: "mov-17", companyId: "vale", shareholderId: "lia", date: "2026-07-09", amount: 120000, eventType: "Entrega em bens", method: "Outro", legacy: false, status: "effective", revision: 1 },
    { id: "mov-18", companyId: "holding", shareholderId: "ana", date: "2026-07-17", amount: 70000, eventType: "Crédito", method: "Transferência interna", legacy: false, status: "effective", revision: 1 },
    { id: "mov-19", companyId: "holding", shareholderId: "horizon", date: "2026-07-24", amount: 135000, eventType: "Capitalização", method: "Capitalização", legacy: false, status: "effective", revision: 1 },
    { id: "mov-20", companyId: "holding", shareholderId: "horizon", date: "2026-08-14", amount: 250000, eventType: "Pagamento", method: "TED", legacy: false, status: "effective", revision: 1 },
    { id: "mov-21", companyId: "aurora", shareholderId: "lia", date: "2026-09-01", amount: 390000, eventType: "Pagamento", method: "PIX", legacy: true, status: "effective", revision: 1, note: "Exemplo demonstrativo de saldo negativo sem retenção." },
    { id: "mov-22", companyId: "iris", shareholderId: "caio", date: "2026-09-01", amount: 260000, eventType: "Pagamento", method: "TED", legacy: false, status: "effective", revision: 1, note: "Exemplo demonstrativo de saldo negativo com retenção." },
  ],
  rules: [
    {
      tone: "blue",
      title: "Grupo sem compensação fiscal",
      text: "O consolidado ajuda a leitura executiva, mas cada empresa mantém seu próprio saldo.",
    },
    {
      tone: "emerald",
      title: "Direito individual preservado",
      text: "Cada sócio visualiza somente o direito, o recebido e o saldo do recorte autorizado.",
    },
    {
      tone: "amber",
      title: "Somente leitura",
      text: "O acesso público não permite lançar, editar, estornar, exportar ou alterar rateios.",
    },
    {
      tone: "indigo",
      title: "Privacidade por escopo",
      text: "A visão exclusiva de sócios usa uma lista própria e não recebe dados de empresas.",
    },
    {
      tone: "rose",
      title: "Excedente permanece visível",
      text: "Saldo negativo exige confirmação e justificativa; ele gera alerta e nunca é compensado automaticamente.",
    },
    {
      tone: "blue",
      title: "Histórico não é apagado",
      text: "Correções criam revisão e o estorno preserva o movimento original na trilha de auditoria.",
    },
    {
      tone: "amber",
      title: "Rateio precisa fechar 100%",
      text: "Um cenário só vira posição oficial depois de conciliar o total e receber documento e justificativa.",
    },
    {
      tone: "indigo",
      title: "Leitura tributária demonstrativa",
      text: "A estimativa agrupa empresa, sócio e mês; a validação fiscal definitiva fica fora deste MVP.",
    },
  ],
});
